configMapGenerator:
- files:
  - application.yml
  name: sample-99995709-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ce99995709acr.azurecr.io/sample-99995709
  newTag: "202409040730"
- name: ceappacr.azurecr.io/sample-99995709
  newTag: "202409020823"
