apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cepg-sa-std-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cepg-sa-std-rwmany
  resources:
    requests:
      storage: 1Gi
