# FROM bellsoft/liberica-openjdk-alpine:17
FROM cepgbaseacr.azurecr.io/mcr.microsoft.com/openjdk/jdk:17-ubuntu

VOLUME /tmp

ARG JAR_FILE=target/*.jar

COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app.jar"]